<?xml version="1.0"?>
<robot name="rosbot"
    xmlns:xacro="http://www.ros.org/wiki/xacro">
    <!-- INCLUDES -->
    <xacro:include filename="$(find rosbot)/urdf/parameters.xacro" />
    <!-- BASE LINK -->
    <link name="base_link">
        <material name="orange"/>
        <!-- pose and inertial -->
        <pose>0 0 0 0 0 0</pose>
        <inertial>
            <origin rpy="0 0 0" xyz="${base_size_x/2} 0 0"/>
            <mass value="${base_mass}"/>
            <xacro:box_inertia mass="${base_mass}" x="${base_size_x}" y="${base_size_y}" z="${base_size_z}"/>
        </inertial>
        <!-- body -->
        <collision name="base_front_collision">
            <origin rpy="0 0 0" xyz="${base_size_x/2} 0 0"/>
            <geometry>
                <box size="${base_size_x} ${base_size_y} ${base_size_z}"/>
            </geometry>
        </collision>
        <visual>
            <origin rpy="0 0 0" xyz="${base_size_x/2} 0 0"/>
            <geometry>
                <box size="${base_size_x} ${base_size_y} ${base_size_z}"/>
            </geometry>
            <material name="green"/>
        </visual>
        <!-- caster front -->
        <collision name="caster_front_collision">
            <origin rpy=" 0 0 0" xyz="${base_size_x} 0 ${-wheel_radius/2}"/>
            <geometry>
                <sphere radius="${wheel_radius/2}"/>
            </geometry>
            <contact_coefficients/>
            <surface>
                <contact>
                    <ode>
                        <kp>${caster_kp}</kp>
                        <kd>${caster_kd}</kd>
                    </ode>
                </contact>
                <friction>
                    <ode>
                        <mu>${caster_mu}</mu>
                        <mu2>${caster_mu2}</mu2>
                        <slip1>${caster_slip1}</slip1>
                        <slip2>${caster_slip2}</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
        <visual>
            <origin rpy=" 0 0 0" xyz="${base_size_x} 0 ${-wheel_radius/2}"/>
            <geometry>
                <sphere radius="${wheel_radius/2}"/>
            </geometry>
            <material name="gray"/>
        </visual>
    </link>
    <!-- LEFT WHEEL LINK -->
    <link name="left_wheel_link">
        <inertial>
            <mass value="${wheel_mass}"/>
            <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
            <xacro:cylinder_inertia mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_width}"/>
        </inertial>
        <collision name="left_wheel_collision">
            <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <surface>
                <contact>
                    <ode>
                        <kp>${wheel_kp}</kp>
                        <kd>${wheel_kd}</kd>
                    </ode>
                </contact>
                <friction>
                    <ode>
                        <mu>${wheel_mu}</mu>
                        <mu2>${wheel_mu2}</mu2>
                        <slip1>${wheel_slip1}</slip1>
                        <slip2>${wheel_slip2}</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
        <visual>
            <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="gray"/>
        </visual>
    </link>
    <!-- LEFT WHEEL JOINT -->
    <joint name="left_motor" type="continuous">
        <origin rpy="0 0 0" xyz="0.0 ${base_size_y/2+wheel_width/2} 0.0"/>
        <child link="left_wheel_link"/>
        <parent link="base_link"/>
        <axis rpy="0 0 0" xyz="0 1 0"/>
        <dynamics damping="${motor_damping}" friction="${motor_friction}"/>
    </joint>
    <!-- RIGHT WHEEL LINK -->
    <link name="right_wheel_link">
        <inertial>
            <mass value="${wheel_mass}"/>
            <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
            <xacro:cylinder_inertia mass="${wheel_mass}" r="${wheel_radius}" l="${wheel_width}"/>
        </inertial>
        <collision name="right_wheel_collision">
            <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <surface>
                <contact>
                    <ode>
                        <kp>${wheel_kp}</kp>
                        <kd>${wheel_kd}</kd>
                    </ode>
                </contact>
                <friction>
                    <ode>
                        <mu>${wheel_mu}</mu>
                        <mu2>${wheel_mu2}</mu2>
                        <slip1>${wheel_slip1}</slip1>
                        <slip2>${wheel_slip2}</slip2>
                    </ode>
                </friction>
            </surface>
        </collision>
        <visual>
            <origin rpy="0 1.5707 1.5707" xyz="0 0 0"/>
            <geometry>
                <cylinder radius="${wheel_radius}" length="${wheel_width}"/>
            </geometry>
            <material name="gray"/>
        </visual>
    </link>
    <!-- RIGHT WHEEL JOINT -->
    <joint name="right_motor" type="continuous">
        <origin rpy="0 0 0" xyz="0 ${-base_size_y/2-wheel_width/2} 0"/>
        <child link="right_wheel_link"/>
        <parent link="base_link"/>
        <axis rpy="0 0 0" xyz="0 1 0"/>
        <dynamics damping="${motor_damping}" friction="${motor_friction}"/>
    </joint>
    <!-- TRANSMISSIONS -->
    <transmission name="left_motor_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="left_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="left_motor">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <transmission name="right_motor_transmission">
        <type>transmission_interface/SimpleTransmission</type>
        <joint name="right_motor">
            <hardwareInterface>hardware_interface/EffortJointInterface</hardwareInterface>
        </joint>
        <actuator name="right_motor">
            <hardwareInterface>EffortJointInterface</hardwareInterface>
            <mechanicalReduction>1</mechanicalReduction>
        </actuator>
    </transmission>
    <!-- GAZEBO CONTROL -->
    <gazebo>
        <plugin name="differential_drive_controller" filename="libgazebo_ros_diff_drive.so">
            <rosDebugLevel>Debug</rosDebugLevel>
            <publishWheelTF>false</publishWheelTF>
            <robotNamespace>/</robotNamespace>
            <publishTf>1</publishTf>
            <publishWheelJointState>false</publishWheelJointState>
            <alwaysOn>true</alwaysOn>
            <updateRate>100.0</updateRate>
            <leftJoint>left_motor</leftJoint>
            <rightJoint>right_motor</rightJoint>
            <wheelSeparation>${base_size_y+wheel_width}</wheelSeparation>
            <wheelDiameter>${2*wheel_radius}</wheelDiameter>
            <broadcastTF>1</broadcastTF>
            <wheelTorque>0.1</wheelTorque>
            <wheelAcceleration>10</wheelAcceleration>
            <commandTopic>cmd_vel</commandTopic>
            <odometryFrame>odom</odometryFrame>
            <odometryTopic>odom</odometryTopic>
            <pose_covariance_diagonal>[1.0, 1.0, 0.0, 0.0, 0.0, 1.0]</pose_covariance_diagonal>
            <twist_covariance_diagonal>[0.01, 0.0, 0.0, 0.0, 0.0, 0.1]</twist_covariance_diagonal>
            <gaussianNoise>0.05</gaussianNoise>
            <robotBaseFrame>base_link</robotBaseFrame>
            <legacyMode>false</legacyMode>
            <publishOdomTF>true</publishOdomTF>
            <odometrySource>world</odometrySource>
        </plugin>
    </gazebo>
    <!-- GAZEBO LIDAR -->
    <link name="lidar_link">
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0"/>
            <geometry>
                <box size="0.01 0.01 0.01"/>
            </geometry>
        </visual>
    </link>
    <joint name="laser_joint" type="fixed">
        <axis xyz="0 1 0" />
        <origin xyz="0.054 0.0 0.030" rpy="0 0 0"/>
        <parent link="base_link"/>
        <child link="lidar_link"/>
    </joint>
    <gazebo reference="lidar_link">
        <sensor type="gpu_ray" name="head_hokuyo_sensor">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>1</update_rate>
            <ray>
                <scan>
                    <horizontal>
                        <samples>180</samples>
                        <resolution>1</resolution>
                        <min_angle>-1.5717</min_angle>
                        <max_angle>1.5717</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.05</min>
                    <max>0.55</max>
                    <resolution>0.001</resolution>
                </range>
                <noise>
                    <type>gaussian</type>
                    <mean>0.0</mean>
                    <stddev>0.01</stddev>
                </noise>
            </ray>
            <plugin name="gazebo_ros_head_hokuyo_controller" filename="libgazebo_ros_gpu_laser.so">
                <topicName>scan</topicName>
                <frameName>lidar_link</frameName>
            </plugin>
        </sensor>
    </gazebo>
    <!-- GAZEBO IMU -->
    <link name="imu_link">
        <inertial>
            <mass value="0.001" />
            <origin xyz="0 0 0" />
            <inertia ixx="0.0" ixy="0.0" ixz="0.0" iyy="0.0" iyz="0.0" izz="0.0" />
        </inertial>
        <visual>
            <origin xyz="0 0 0" rpy="0 0 0" />
            <geometry>
                <box size = "0.005 0.005 0.005"/>
            </geometry>
        </visual>
        <collision>
            <geometry>
                <box size = "0.005 0.005 0.005"/>
            </geometry>
        </collision>
    </link>

    <joint name="imu_joint" type="fixed">
        <axis xyz="0 0 0"/>
        <origin xyz="0.080 0 0.01" rpy="0 0 0" />
        <parent link="base_link"/>
        <child link="imu_link" />
    </joint>

    <gazebo>
        <plugin name="imu_plugin" filename="libgazebo_ros_imu.so">
            <alwaysOn>true</alwaysOn>
            <bodyName>imu_link</bodyName>
            <frameName>base_link</frameName>
            <topicName>imu</topicName>
            <serviceName>imu_service</serviceName>
            <gaussianNoise>0.01</gaussianNoise>
            <updateRate>100.0</updateRate>
        </plugin>
    </gazebo>
    <gazebo reference="base_link">
        <material>Gazebo/Green</material>
    </gazebo>
    <gazebo reference="left_wheel_link">
        <material>Gazebo/DarkGrey</material>
    </gazebo>
    <gazebo reference="right_wheel_link">
        <material>Gazebo/DarkGrey</material>
    </gazebo>
</robot>